### ISSUE TITLE
Can't "stop fishing" the program stops responding 100% of the time. Also..

### ISSUE THREAD

**Issue by deadbandit** [Siterizer/new-world-fishing-bot#25] opened 2021-10-02 20:08 UTC
It seem the maximum amount of time I can wait to hook a fish is 13seconds, It almost always takes longer.

**Comment by deadbandit** [comment] 2021-10-02 21:02
The not being able to stop fishing is alright, since I can force the stop through task manager, but I can't catch any fish because it literally never waits long enough, even after I set the time to 20-30 seconds. It's like at 13 seconds max.

**Comment by rogeriocamorim** [comment] 2021-10-03 01:11
Upvote this one.

**Comment by Siterizer** [comment] 2021-10-03 08:39
@rogeriocamorim @deadbandit Could You pls send here a screen with terminal output? Can't guess what is wrong  but this will help

**Comment by deadbandit** [comment] 2021-10-03 20:28
> @rogeriocamorim @deadbandit Could You pls send here a screen with terminal output? Can't guess what is wrong but this will help

I don't know how to do that.

**Comment by rogeriocamorim** [comment] 2021-10-04 03:08
There is no termial output.
Simple when you start fishing you can not stop unless you close the terminal

**Comment by JKamsker** [comment] 2021-10-04 23:56
You can stop. 
The issue is that the app is single threaded and the gui only respons between each console message.
Best way of stopping is waiting till it waits for the fish.

**Comment by Siterizer** [comment] 2021-10-08 00:18
i will close the issue, that thing (i hope) will be covered in next update

**Closed by Siterizer** 2021-10-08 00:18 UTC
Labels: help wanted
