### ISSUE TITLE
Login blocked notification

### ISSUE THREAD

**Issue by hacku5** [Siterizer/new-world-fishing-bot#140] opened 2021-10-15 21:00 UTC
I did test 1.2.1 version, new world kicking me with login blocked notification. But was very well running 8-9 hours.
I'm reporting this for users to be careful
#135

**Comment by Szak0** [comment] 2021-10-15 21:19
Do you think is it because the release 1.2.1 or you may used old versions a lot before?

**Comment by Szak0** [comment] 2021-10-15 21:26
> I did test 1.2.1 version, new world kicking me with login blocked notification. But was very well running 8-9 hours. I'm reporting this for users to be careful #135

Can you attach a screenshot?

**Comment by Mattallica81** [comment] 2021-10-15 23:22
Scary stuff do you guys run this on a separate steam account or on your main character account?

**Comment by Barrery** [comment] 2021-10-16 12:09
![rbHw4zl3RY-B-G2Hzb9RJg](https://user-images.githubusercontent.com/11139926/137586708-8b1b4234-a7a9-46f8-b60e-e5b62d4f51a2.png)

This happens after 15 mins.

**Comment by Siterizer** [comment] 2021-10-16 12:12
From what i see a lot of 'normal' players have the same issue:
https://forums.newworld.com/t/login-blocked-suspicious-software-or-corrupted-install-detected/383397/23
This is a good question what is going on. 
@Barrery @hacku5 you run the bot with .exe or with python?

**Comment by Runelover1** [comment] 2021-10-16 14:32
I been using for last 5hrs no problem here, but I also dont stand around nude looking like a bot

**Comment by hacku5** [comment] 2021-10-16 15:39
> From what i see a lot of 'normal' players have the same issue: https://forums.newworld.com/t/login-blocked-suspicious-software-or-corrupted-install-detected/383397/23 This is a good question what is going on. @Barrery @hacku5 you run the bot with .exe or with python?

Run with python, wich better ?

**Comment by Barrery** [comment] 2021-10-16 16:10
@Siterizer i was using this bot from two pcs, 72 hrs no kicks nothing, then this morning i got this message but only on second pc, first was still working, both sides using exe. Wish to ask you add rename function, so the process wont be named as fisher bot

**Comment by Siterizer** [comment] 2021-10-16 16:21
@hacku5 wanted just to know. IT looks like there is no difference between using pyton or exe. My idea ja The game is not looking for external running app. He only sees that your game character is suspicius

**Comment by Antikythera810** [comment] 2021-10-16 16:23
I have just tested this for 1 hour with the a clean download of the new 1.2.1 version and I was not able to reproduce this error.

@Barrery are all 3 of your PCs matching in regards to installed applications? I have seen reports of LED controller programs and other items like that causing these kinds of errors. It seems very strange that only one of your accounts would be targeted and not the other two if this was related to the program itself.

**Comment by Barrery** [comment] 2021-10-16 16:26
![Screenshot_20211016-202548_Chrome](https://user-images.githubusercontent.com/11139926/137594979-651920b2-47c8-4552-9545-50fcefdb11e4.jpg)

**Comment by Runelover1** [comment] 2021-10-16 16:28
ahhh that part of the ui ya mybad was thinking u was meaning in task manger

**Comment by Antikythera810** [comment] 2021-10-16 16:31
You can rename that section from the bot.py script if you use the python version.

![image](https://user-images.githubusercontent.com/27442989/137595119-8162770f-0e8c-4922-a1d1-e592f44b9dae.png)

**Comment by hacku5** [comment] 2021-10-16 17:09
> Python sürümünü kullanıyorsanız, bu bölümü bot.py betiğinden yeniden adlandırabilirsiniz.
> 
> ![resim](https://user-images.githubusercontent.com/27442989/137595119-8162770f-0e8c-4922-a1d1-e592f44b9dae.png)

I'm using this method mostly every time

**Comment by 4LAU** [comment] 2021-10-16 17:34
i'd actually argue that v1.2.1_anti_afk is more bot-like than the one where you stand still. tried running this overnight, at some point got kicked off with the same warning. running left then right at the same interval every few minutes isn't really normal player behavior lol.

**Comment by hacku5** [comment] 2021-10-16 18:25
I think someone reported me lol

**Comment by Antikythera810** [comment] 2021-10-16 19:02
I would always recommend fishing from one of the houses in Weavers Fen that has access to the water - you will be invisible to other players when inside the house.

**Comment by unuhuynh** [comment] 2021-10-17 01:01
> i'd actually argue that v1.2.1_anti_afk is more bot-like than the one where you stand still. tried running this overnight, at some point got kicked off with the same warning. running left then right at the same interval every few minutes isn't really normal player behavior lol.

i still run on 1.2 temp fix and so far i have not disconnected for 10+ period, i have someone tested 1.2.1 and still didn't get kicked with that screen, just a regular afk screenshot. 

Since they reverted the anti-afk I will test 1.2 standing still to see what is the middle ground.

**Comment by Siterizer** [comment] 2021-10-17 05:51
What amazes me is the fact that Amazon, having EAC, does not even think about searching for bots by looking at active processes in the background (This is evidenced by the fact that only some of the users get the "Login Blocked" message). 
  So they have to check the behavior of the users, and once again, if I only some users get this information I'm pretty sure they are doing too obviously. A message for users to users: **Be smart**. 
  Change timeouts in the config, put on the armor / weapons, do not stand in places where there are a lot of people 
  (maybe a lot of reports + fishing = Login blocked message). 
  
  I have no more to add, I will close the topic

**Closed by Siterizer** 2021-10-17 05:51 UTC
Labels: help wanted
